name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Choose the test suite to run'
        type: choice
        options:
          - all
          - smoke
        default: all

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run all tests
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.test_suite == 'all' }}
        run: npx playwright test

      - name: Run smoke tests
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.test_suite == 'smoke' }}
        run: npx playwright test --grep @smoke

      - name: Upload Playwright report
        if: ${{ !cancelled() && success() && hashFiles('playwright-report/index.html') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30